---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/golang-ci
    tag: latest

inputs:
- name: grootfs-release-master
- name: grootfs-release-version

outputs:
- name: build-grootfs

run:
  path: src/code.cloudfoundry.org/grootfs/ci/scripts/build-grootfs.sh
